  # PLANTILLA DE PLAYBOOK
  
  # Para ejecutar nuestro playbook:
  #  > ansible-playbook -i <fichero_inventario> <fichero_playbook>
  
  # Contra qué máquinas/entornos vamos a trabajar
- hosts: test
  gather_facts: True
  remote_user: root
  tasks:
    
    # Creación de un CUSTOM FACT constante
    # Crear un directorio en la máquina con ruta: /etc/ansible/facts.d
    - name: Crear directorio de CUSTOM FACTS en entorno remoto
      file:
        path: /etc/ansible/facts.d
        state: directory
      tags:
        - create_facts
    
    # Crear un fichero con extensión .fact
    # El contenido del fichero, con el valor del fact
    - name: Copiar el fichero con el CUSTOM FACT en entorno remoto
      copy:
        src: mi_custom_fact.fact
        dest: /etc/ansible/facts.d/mi_custom_fact.fact
        mode: '644'
      tags:
        - create_facts
    
    - name: Generar el fichero con el CUSTOM FACT en entorno remoto
      copy:
        content: '"Segundo fichero de fact"'
        dest: /etc/ansible/facts.d/mi_custom_fact_2.fact
        mode: '644'
      tags:
        - create_facts
        

## CUSTOM FACT DINÁMICO
# un ejecutable
    - name: Copiar el fichero con el CUSTOM FACT en entorno remoto
      copy:
        src: mi_custom_fact_dinamico.fact
        dest: /etc/ansible/facts.d/mi_custom_fact_dinamico.fact
        mode: '755'
      tags:
        - create_facts

    - name: Copiar el fichero con el CUSTOM FACT en entorno remoto
      copy:
        src: mi_custom_fact_dinamico_python.fact
        dest: /etc/ansible/facts.d/mi_custom_fact_dinamico.fact
        mode: '755'
      tags:
        - create_facts
        
## MENSAJES DE DEBUG
    - name: Mostrar informacion del fact
      debug:
        #msg: "Este es el contenido de {{ ansible_local }}"
        msg: "{{ ansible_local }}"
    
    - name: Mostrar informacion del fact custom
      debug:
        msg: "CONTENIDO:: {{ ansible_local.mi_custom_fact }}"   